### PR TITLE
Gradle

### PR DESCRIPTION
**Pull request by shadowfacts**
- Add compile time deps to `build.gradle`
- Declare source and target compatibility on the root project to automatically set them in the IDEA config.
- Remove redundant application of the IDEA plugin, it is applied by FG
- Add other IDEA files to `.gitignore`
- Add CC API to `src/api/java`

### CODE REVIEW

**Comment by jamesbirtles** [comment]
Presumably you are going to do something with the computercraft api, but no need to include the api in the repo

**Comment by shadowfacts** [comment]
I'm not but you are, and as (to my knowledge) dan200 doesn't provide a publicly accessible deobfuscated version of CC, this is the best way to prevent compile time errors.

**Comment by jamesbirtles** [comment]
Oh totally forgot about bundled cable stuffs _derp_, I still don't want to include the api in my repo.

**Comment by shadowfacts** [comment]
Yea, it's not optimal, but I'm not sure if there's any better way :V

**Comment by jamesbirtles** [comment]
`artifactPattern "http://addons-origin.cursecdn.com/files/2244/605/[module][revision].[ext]"`
and
`compile "dan200:ComputerCraft:1.74"`

seems to work for me

**Comment by shadowfacts** [comment]
Huh, I'd presumed that wouldn't work because the CF version is obfuscated.

**Comment by jamesbirtles** [comment]
I'm going to merge this anyway

**Pull request merged**
